import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hollywood = localFont({
  src: [
    {
      path: "../public/fonts/HollyWoodFont/SF Hollywood Hills.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/HollyWoodFont/SF Hollywood Hills Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/HollyWoodFont/SF Hollywood Hills Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/HollyWoodFont/SF Hollywood Hills Bold Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-hollywood",
});

const crosner = localFont({
  src: "../public/fonts/Crosner-Regular-FREE.otf",
  variable: "--font-crosner",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hollywood.variable} ${crosner.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
